language: java

env:
  global:
    - MAVEN_OPTS="-Xmx512M -XX:+ExitOnOutOfMemoryError"
    - MAVEN_SKIP_CHECKS_AND_DOCS="-Dair.check.skip-all=true -Dmaven.javadoc.skip=true"
    - MAVEN_FAST_INSTALL="-DskipTests $MAVEN_SKIP_CHECKS_AND_DOCS -B -q -T C1"
  matrix:
    - MAVEN_CHECKS=true UPLOAD_ARTIFACTS=true
    - TEST_SPECIFIC_MODULES=presto-tests
    - TEST_SPECIFIC_MODULES=presto-raptor
    - TEST_SPECIFIC_MODULES=presto-accumulo
    - TEST_SPECIFIC_MODULES=presto-cassandra,presto-hive,presto-kafka,presto-mysql,presto-postgresql,presto-redis
    - TEST_OTHER_MODULES=!presto-tests,!presto-raptor,!presto-accumulo,!presto-cassandra,!presto-hive,!presto-kafka,!presto-mysql,!presto-postgresql,!presto-redis,!presto-docs,!presto-server,!presto-server-rpm
    - PRODUCT_TESTS=true
    - HIVE_TESTS=true

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.m2/repository

services:
  - docker

before_install:
  # This is needed until Travis #4629 is fixed (https://github.com/travis-ci/travis-ci/issues/4629)
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

install:
  - echo "lets make it quick."

script:
  - |
    [[ $(( $RANDOM % 6 )) -ne 0 ]] && echo 'click'

before_cache:
  # Make the cache stable between builds by removing build output
  - rm -rf $HOME/.m2/repository/com/facebook

notifications:
  slack:
    secure: V5eyoGShxFoCcYJcp858vf/T6gC9KeMxL0C1EElcpZRcKBrIVZzvhek3HLHxZOxlghqnvNVsyDtU3u5orkEaAXeXj5c2dN+4XBsAB9oeN5MtQ0Z3VLAhZDqKIW1LzcXrq4DpzM0PkGhjfjum/P94/qFYk0UckPtB6a341AuYRo8=

after_script:
- |
  if [[ -v DEPLOY_S3_ACCESS_KEY ]]; then
    sudo pip install awscli
    export AWS_ACCESS_KEY_ID=${DEPLOY_S3_ACCESS_KEY}
    export AWS_SECRET_ACCESS_KEY=${DEPLOY_S3_SECRET_KEY}
    JOB_STATUS=$( [ "$TRAVIS_TEST_RESULT" == "0" ] && echo SUCCESS || echo FAILURE )
    JOB_ARTIFACTS_PATH_PREFIX=s3://${DEPLOY_S3_BUCKET}/travis_build_artifacts/${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}/${TRAVIS_BUILD_NUMBER}/travis_jobs/${TRAVIS_JOB_NUMBER}-run
    JOB_RUN_ATTEMPTS=$( aws s3 ls ${JOB_ARTIFACTS_PATH_PREFIX} | wc -l | tr -d '[:space:]' )
    aws s3 cp \
      s3://archive.travis-ci.org/jobs/${TRAVIS_JOB_ID}/log.txt \
      ${JOB_ARTIFACTS_PATH_PREFIX}-$((JOB_RUN_ATTEMPTS + 1))-${JOB_STATUS}/log.txt
  fi
