version: '2'
services:

  java-8-base:
    image: 'teradatalabs/centos6-java8-oracle:jdk1.8.0_92-80a011f'
    env_file:
      - ../../../target/classes/presto.env

  presto-volumes:
    image: 'busybox'
    volumes:
      - /docker/volumes/presto/presto-product-tests
      - /docker/volumes/presto/presto-product-tests/target/classes
      - /docker/volumes/presto/presto-server/target/
      - /docker/volumes/presto/presto-cli/target/
      - /docker/volumes/tempto

  hadoop-master:
    extends:
      service: java-8-base
    image: 'teradatalabs/cdh5-hive:2'
    hostname: hadoop-master
    ports:
      - '1080:1080'
      - '8020:8020'
      - '8088:8088'
      - '9083:9083'
      - '10000:10000'
      - '50070:50070'
      - '50075:50075'
    volumes_from:
      - presto-volumes

  presto-master:
    extends:
      service: java-8-base
    hostname: presto-master
    ports:
      - '8080:8080'
    depends_on:
      - hadoop-master
    volumes_from:
      - presto-volumes

  application-runner:
    extends:
      service: java-8-base
    hostname: application-runner
    depends_on:
      - presto-master
    volumes_from:
      - presto-volumes
