version: '2'
services:
  hadoop-master:
    hostname: hadoop-master
    image: 'teradatalabs/cdh5-hive-kerberized:3'
    ports:
      - '1080:1080'
      - '8020:8020'
      - '8088:8088'
      - '9083:9083'
      - '10000:10000'
      - '50070:50070'
      - '50075:50075'

  presto-master:
    hostname: presto-master
    # cdh5-hive-kerberized contains keytabs and the `krb5.conf` within
    image: 'teradatalabs/cdh5-hive-kerberized:3'
    depends_on:
      - 'hadoop-master'
    command: /docker/volumes/presto/presto-product-tests/conf/docker/files/presto-launcher-wrapper.sh singlenode-kerberized run
    volumes_from:
      - presto-volumes
    env_file:
      - ../../../target/classes/presto.env

  application-runner:
    hostname: application-runner
    # cdh5-hive-kerberized contains keytabs and the `krb5.conf` within
    image: 'teradatalabs/cdh5-hive-kerberized:3'
    depends_on:
      - 'presto-master'
    volumes_from:
      - presto-volumes
    env_file:
      - ../../../target/classes/presto.env

  presto-volumes:
    image: 'busybox'
    volumes:
      - /docker/volumes/presto/presto-product-tests
      - /docker/volumes/presto/presto-product-tests/target/classes
      - /docker/volumes/presto/presto-server/target/
      - /docker/volumes/presto/presto-cli/target/
      - /docker/volumes/tempto
